id: P009206
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:28:01.206621
source_metadata:
  id: bdr:W8LS16725
  title: གསོལ་འདེབས་སྐྱབས་སེམས་དུག་ཕྱུག་དག་གཙང་དང་བཅས་པ།
  author: ''
  volumes:
    06cec8496b4845619c186d8334f89201:
      image_group_id: I8LS16733
      title: ''
      volume_number: 1
      total_pages: 576
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
